gText_Birch_Welcome::
	.string "Greetings!\n"
	.string "My name is Professor TREE.\p"
	.string "Welcome to the NAME region, a land\n"
	.string "where the seasons swing from one\p"
	.string "one to another like the sway\n"
	.string "of a pendulum.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "I study this region, and how it's\n"
	.string "POKémon are affected by it's\p"
	.string "erratic seasons.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a guy?\n"
	.string "Or are you a gal?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
